package com.web.testssm.entity;

import java.io.Serializable;
import java.util.Date;

public class KwKcap implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.kch
     *
     * @mbg.generated
     */
    private String kch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.ks_id
     *
     * @mbg.generated
     */
    private String ksId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.kssj
     *
     * @mbg.generated
     */
    private Date kssj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.kssd
     *
     * @mbg.generated
     */
    private String kssd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.kcxh
     *
     * @mbg.generated
     */
    private String kcxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.xy
     *
     * @mbg.generated
     */
    private String xy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.xymc
     *
     * @mbg.generated
     */
    private String xymc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.ksly
     *
     * @mbg.generated
     */
    private String ksly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.kcdm
     *
     * @mbg.generated
     */
    private String kcdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.kmmc
     *
     * @mbg.generated
     */
    private String kmmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.rkjs
     *
     * @mbg.generated
     */
    private String rkjs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.ksfs
     *
     * @mbg.generated
     */
    private String ksfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.xqh
     *
     * @mbg.generated
     */
    private String xqh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.xqmc
     *
     * @mbg.generated
     */
    private String xqmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.ksrs
     *
     * @mbg.generated
     */
    private Integer ksrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.kcsyrs
     *
     * @mbg.generated
     */
    private Integer kcsyrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.js_id
     *
     * @mbg.generated
     */
    private String jsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.jsmc
     *
     * @mbg.generated
     */
    private String jsmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.zydm
     *
     * @mbg.generated
     */
    private String zydm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.zymc
     *
     * @mbg.generated
     */
    private String zymc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.nj
     *
     * @mbg.generated
     */
    private String nj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.xq
     *
     * @mbg.generated
     */
    private String xq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.is_jsdz
     *
     * @mbg.generated
     */
    private String isJsdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.cjr
     *
     * @mbg.generated
     */
    private String cjr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_kcap.cjsj
     *
     * @mbg.generated
     */
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kw_kcap
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.id
     *
     * @return the value of kw_kcap.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.id
     *
     * @param id the value for kw_kcap.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.kch
     *
     * @return the value of kw_kcap.kch
     *
     * @mbg.generated
     */
    public String getKch() {
        return kch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.kch
     *
     * @param kch the value for kw_kcap.kch
     *
     * @mbg.generated
     */
    public void setKch(String kch) {
        this.kch = kch == null ? null : kch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.ks_id
     *
     * @return the value of kw_kcap.ks_id
     *
     * @mbg.generated
     */
    public String getKsId() {
        return ksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.ks_id
     *
     * @param ksId the value for kw_kcap.ks_id
     *
     * @mbg.generated
     */
    public void setKsId(String ksId) {
        this.ksId = ksId == null ? null : ksId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.kssj
     *
     * @return the value of kw_kcap.kssj
     *
     * @mbg.generated
     */
    public Date getKssj() {
        return kssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.kssj
     *
     * @param kssj the value for kw_kcap.kssj
     *
     * @mbg.generated
     */
    public void setKssj(Date kssj) {
        this.kssj = kssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.kssd
     *
     * @return the value of kw_kcap.kssd
     *
     * @mbg.generated
     */
    public String getKssd() {
        return kssd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.kssd
     *
     * @param kssd the value for kw_kcap.kssd
     *
     * @mbg.generated
     */
    public void setKssd(String kssd) {
        this.kssd = kssd == null ? null : kssd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.kcxh
     *
     * @return the value of kw_kcap.kcxh
     *
     * @mbg.generated
     */
    public String getKcxh() {
        return kcxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.kcxh
     *
     * @param kcxh the value for kw_kcap.kcxh
     *
     * @mbg.generated
     */
    public void setKcxh(String kcxh) {
        this.kcxh = kcxh == null ? null : kcxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.xy
     *
     * @return the value of kw_kcap.xy
     *
     * @mbg.generated
     */
    public String getXy() {
        return xy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.xy
     *
     * @param xy the value for kw_kcap.xy
     *
     * @mbg.generated
     */
    public void setXy(String xy) {
        this.xy = xy == null ? null : xy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.xymc
     *
     * @return the value of kw_kcap.xymc
     *
     * @mbg.generated
     */
    public String getXymc() {
        return xymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.xymc
     *
     * @param xymc the value for kw_kcap.xymc
     *
     * @mbg.generated
     */
    public void setXymc(String xymc) {
        this.xymc = xymc == null ? null : xymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.ksly
     *
     * @return the value of kw_kcap.ksly
     *
     * @mbg.generated
     */
    public String getKsly() {
        return ksly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.ksly
     *
     * @param ksly the value for kw_kcap.ksly
     *
     * @mbg.generated
     */
    public void setKsly(String ksly) {
        this.ksly = ksly == null ? null : ksly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.kcdm
     *
     * @return the value of kw_kcap.kcdm
     *
     * @mbg.generated
     */
    public String getKcdm() {
        return kcdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.kcdm
     *
     * @param kcdm the value for kw_kcap.kcdm
     *
     * @mbg.generated
     */
    public void setKcdm(String kcdm) {
        this.kcdm = kcdm == null ? null : kcdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.kmmc
     *
     * @return the value of kw_kcap.kmmc
     *
     * @mbg.generated
     */
    public String getKmmc() {
        return kmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.kmmc
     *
     * @param kmmc the value for kw_kcap.kmmc
     *
     * @mbg.generated
     */
    public void setKmmc(String kmmc) {
        this.kmmc = kmmc == null ? null : kmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.rkjs
     *
     * @return the value of kw_kcap.rkjs
     *
     * @mbg.generated
     */
    public String getRkjs() {
        return rkjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.rkjs
     *
     * @param rkjs the value for kw_kcap.rkjs
     *
     * @mbg.generated
     */
    public void setRkjs(String rkjs) {
        this.rkjs = rkjs == null ? null : rkjs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.ksfs
     *
     * @return the value of kw_kcap.ksfs
     *
     * @mbg.generated
     */
    public String getKsfs() {
        return ksfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.ksfs
     *
     * @param ksfs the value for kw_kcap.ksfs
     *
     * @mbg.generated
     */
    public void setKsfs(String ksfs) {
        this.ksfs = ksfs == null ? null : ksfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.xqh
     *
     * @return the value of kw_kcap.xqh
     *
     * @mbg.generated
     */
    public String getXqh() {
        return xqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.xqh
     *
     * @param xqh the value for kw_kcap.xqh
     *
     * @mbg.generated
     */
    public void setXqh(String xqh) {
        this.xqh = xqh == null ? null : xqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.xqmc
     *
     * @return the value of kw_kcap.xqmc
     *
     * @mbg.generated
     */
    public String getXqmc() {
        return xqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.xqmc
     *
     * @param xqmc the value for kw_kcap.xqmc
     *
     * @mbg.generated
     */
    public void setXqmc(String xqmc) {
        this.xqmc = xqmc == null ? null : xqmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.ksrs
     *
     * @return the value of kw_kcap.ksrs
     *
     * @mbg.generated
     */
    public Integer getKsrs() {
        return ksrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.ksrs
     *
     * @param ksrs the value for kw_kcap.ksrs
     *
     * @mbg.generated
     */
    public void setKsrs(Integer ksrs) {
        this.ksrs = ksrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.kcsyrs
     *
     * @return the value of kw_kcap.kcsyrs
     *
     * @mbg.generated
     */
    public Integer getKcsyrs() {
        return kcsyrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.kcsyrs
     *
     * @param kcsyrs the value for kw_kcap.kcsyrs
     *
     * @mbg.generated
     */
    public void setKcsyrs(Integer kcsyrs) {
        this.kcsyrs = kcsyrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.js_id
     *
     * @return the value of kw_kcap.js_id
     *
     * @mbg.generated
     */
    public String getJsId() {
        return jsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.js_id
     *
     * @param jsId the value for kw_kcap.js_id
     *
     * @mbg.generated
     */
    public void setJsId(String jsId) {
        this.jsId = jsId == null ? null : jsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.jsmc
     *
     * @return the value of kw_kcap.jsmc
     *
     * @mbg.generated
     */
    public String getJsmc() {
        return jsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.jsmc
     *
     * @param jsmc the value for kw_kcap.jsmc
     *
     * @mbg.generated
     */
    public void setJsmc(String jsmc) {
        this.jsmc = jsmc == null ? null : jsmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.zydm
     *
     * @return the value of kw_kcap.zydm
     *
     * @mbg.generated
     */
    public String getZydm() {
        return zydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.zydm
     *
     * @param zydm the value for kw_kcap.zydm
     *
     * @mbg.generated
     */
    public void setZydm(String zydm) {
        this.zydm = zydm == null ? null : zydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.zymc
     *
     * @return the value of kw_kcap.zymc
     *
     * @mbg.generated
     */
    public String getZymc() {
        return zymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.zymc
     *
     * @param zymc the value for kw_kcap.zymc
     *
     * @mbg.generated
     */
    public void setZymc(String zymc) {
        this.zymc = zymc == null ? null : zymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.nj
     *
     * @return the value of kw_kcap.nj
     *
     * @mbg.generated
     */
    public String getNj() {
        return nj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.nj
     *
     * @param nj the value for kw_kcap.nj
     *
     * @mbg.generated
     */
    public void setNj(String nj) {
        this.nj = nj == null ? null : nj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.xq
     *
     * @return the value of kw_kcap.xq
     *
     * @mbg.generated
     */
    public String getXq() {
        return xq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.xq
     *
     * @param xq the value for kw_kcap.xq
     *
     * @mbg.generated
     */
    public void setXq(String xq) {
        this.xq = xq == null ? null : xq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.is_jsdz
     *
     * @return the value of kw_kcap.is_jsdz
     *
     * @mbg.generated
     */
    public String getIsJsdz() {
        return isJsdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.is_jsdz
     *
     * @param isJsdz the value for kw_kcap.is_jsdz
     *
     * @mbg.generated
     */
    public void setIsJsdz(String isJsdz) {
        this.isJsdz = isJsdz == null ? null : isJsdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.cjr
     *
     * @return the value of kw_kcap.cjr
     *
     * @mbg.generated
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.cjr
     *
     * @param cjr the value for kw_kcap.cjr
     *
     * @mbg.generated
     */
    public void setCjr(String cjr) {
        this.cjr = cjr == null ? null : cjr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_kcap.cjsj
     *
     * @return the value of kw_kcap.cjsj
     *
     * @mbg.generated
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_kcap.cjsj
     *
     * @param cjsj the value for kw_kcap.cjsj
     *
     * @mbg.generated
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kw_kcap
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", kch=").append(kch);
        sb.append(", ksId=").append(ksId);
        sb.append(", kssj=").append(kssj);
        sb.append(", kssd=").append(kssd);
        sb.append(", kcxh=").append(kcxh);
        sb.append(", xy=").append(xy);
        sb.append(", xymc=").append(xymc);
        sb.append(", ksly=").append(ksly);
        sb.append(", kcdm=").append(kcdm);
        sb.append(", kmmc=").append(kmmc);
        sb.append(", rkjs=").append(rkjs);
        sb.append(", ksfs=").append(ksfs);
        sb.append(", xqh=").append(xqh);
        sb.append(", xqmc=").append(xqmc);
        sb.append(", ksrs=").append(ksrs);
        sb.append(", kcsyrs=").append(kcsyrs);
        sb.append(", jsId=").append(jsId);
        sb.append(", jsmc=").append(jsmc);
        sb.append(", zydm=").append(zydm);
        sb.append(", zymc=").append(zymc);
        sb.append(", nj=").append(nj);
        sb.append(", xq=").append(xq);
        sb.append(", isJsdz=").append(isJsdz);
        sb.append(", cjr=").append(cjr);
        sb.append(", cjsj=").append(cjsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}