package com.web.testssm.entity;

import java.io.Serializable;

public class KwXkXx implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_xk_xx.nd
     *
     * @mbg.generated
     */
    private String nd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_xk_xx.xq
     *
     * @mbg.generated
     */
    private String xq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_xk_xx.kcxh
     *
     * @mbg.generated
     */
    private String kcxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_xk_xx.kch
     *
     * @mbg.generated
     */
    private String kch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_xk_xx.xz
     *
     * @mbg.generated
     */
    private String xz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_xk_xx.jsgh
     *
     * @mbg.generated
     */
    private String jsgh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_xk_xx.kkxy
     *
     * @mbg.generated
     */
    private String kkxy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_xk_xx.zy
     *
     * @mbg.generated
     */
    private String zy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_xk_xx.nj
     *
     * @mbg.generated
     */
    private String nj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kw_xk_xx.yyxz
     *
     * @mbg.generated
     */
    private String yyxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kw_xk_xx
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_xk_xx.nd
     *
     * @return the value of kw_xk_xx.nd
     *
     * @mbg.generated
     */
    public String getNd() {
        return nd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_xk_xx.nd
     *
     * @param nd the value for kw_xk_xx.nd
     *
     * @mbg.generated
     */
    public void setNd(String nd) {
        this.nd = nd == null ? null : nd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_xk_xx.xq
     *
     * @return the value of kw_xk_xx.xq
     *
     * @mbg.generated
     */
    public String getXq() {
        return xq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_xk_xx.xq
     *
     * @param xq the value for kw_xk_xx.xq
     *
     * @mbg.generated
     */
    public void setXq(String xq) {
        this.xq = xq == null ? null : xq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_xk_xx.kcxh
     *
     * @return the value of kw_xk_xx.kcxh
     *
     * @mbg.generated
     */
    public String getKcxh() {
        return kcxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_xk_xx.kcxh
     *
     * @param kcxh the value for kw_xk_xx.kcxh
     *
     * @mbg.generated
     */
    public void setKcxh(String kcxh) {
        this.kcxh = kcxh == null ? null : kcxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_xk_xx.kch
     *
     * @return the value of kw_xk_xx.kch
     *
     * @mbg.generated
     */
    public String getKch() {
        return kch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_xk_xx.kch
     *
     * @param kch the value for kw_xk_xx.kch
     *
     * @mbg.generated
     */
    public void setKch(String kch) {
        this.kch = kch == null ? null : kch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_xk_xx.xz
     *
     * @return the value of kw_xk_xx.xz
     *
     * @mbg.generated
     */
    public String getXz() {
        return xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_xk_xx.xz
     *
     * @param xz the value for kw_xk_xx.xz
     *
     * @mbg.generated
     */
    public void setXz(String xz) {
        this.xz = xz == null ? null : xz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_xk_xx.jsgh
     *
     * @return the value of kw_xk_xx.jsgh
     *
     * @mbg.generated
     */
    public String getJsgh() {
        return jsgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_xk_xx.jsgh
     *
     * @param jsgh the value for kw_xk_xx.jsgh
     *
     * @mbg.generated
     */
    public void setJsgh(String jsgh) {
        this.jsgh = jsgh == null ? null : jsgh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_xk_xx.kkxy
     *
     * @return the value of kw_xk_xx.kkxy
     *
     * @mbg.generated
     */
    public String getKkxy() {
        return kkxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_xk_xx.kkxy
     *
     * @param kkxy the value for kw_xk_xx.kkxy
     *
     * @mbg.generated
     */
    public void setKkxy(String kkxy) {
        this.kkxy = kkxy == null ? null : kkxy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_xk_xx.zy
     *
     * @return the value of kw_xk_xx.zy
     *
     * @mbg.generated
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_xk_xx.zy
     *
     * @param zy the value for kw_xk_xx.zy
     *
     * @mbg.generated
     */
    public void setZy(String zy) {
        this.zy = zy == null ? null : zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_xk_xx.nj
     *
     * @return the value of kw_xk_xx.nj
     *
     * @mbg.generated
     */
    public String getNj() {
        return nj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_xk_xx.nj
     *
     * @param nj the value for kw_xk_xx.nj
     *
     * @mbg.generated
     */
    public void setNj(String nj) {
        this.nj = nj == null ? null : nj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kw_xk_xx.yyxz
     *
     * @return the value of kw_xk_xx.yyxz
     *
     * @mbg.generated
     */
    public String getYyxz() {
        return yyxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kw_xk_xx.yyxz
     *
     * @param yyxz the value for kw_xk_xx.yyxz
     *
     * @mbg.generated
     */
    public void setYyxz(String yyxz) {
        this.yyxz = yyxz == null ? null : yyxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kw_xk_xx
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nd=").append(nd);
        sb.append(", xq=").append(xq);
        sb.append(", kcxh=").append(kcxh);
        sb.append(", kch=").append(kch);
        sb.append(", xz=").append(xz);
        sb.append(", jsgh=").append(jsgh);
        sb.append(", kkxy=").append(kkxy);
        sb.append(", zy=").append(zy);
        sb.append(", nj=").append(nj);
        sb.append(", yyxz=").append(yyxz);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}