package com.web.testssm.entity;

import java.io.Serializable;

public class TJxZy implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jx_zy.zy
     *
     * @mbg.generated
     */
    private String zy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jx_zy.mc
     *
     * @mbg.generated
     */
    private String mc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jx_zy.ywmc
     *
     * @mbg.generated
     */
    private String ywmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jx_zy.xy
     *
     * @mbg.generated
     */
    private String xy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jx_zy.xsh
     *
     * @mbg.generated
     */
    private String xsh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jx_zy.lb
     *
     * @mbg.generated
     */
    private String lb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jx_zy.zygb
     *
     * @mbg.generated
     */
    private String zygb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jx_zy.zt
     *
     * @mbg.generated
     */
    private String zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_jx_zy
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jx_zy.zy
     *
     * @return the value of t_jx_zy.zy
     *
     * @mbg.generated
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jx_zy.zy
     *
     * @param zy the value for t_jx_zy.zy
     *
     * @mbg.generated
     */
    public void setZy(String zy) {
        this.zy = zy == null ? null : zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jx_zy.mc
     *
     * @return the value of t_jx_zy.mc
     *
     * @mbg.generated
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jx_zy.mc
     *
     * @param mc the value for t_jx_zy.mc
     *
     * @mbg.generated
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jx_zy.ywmc
     *
     * @return the value of t_jx_zy.ywmc
     *
     * @mbg.generated
     */
    public String getYwmc() {
        return ywmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jx_zy.ywmc
     *
     * @param ywmc the value for t_jx_zy.ywmc
     *
     * @mbg.generated
     */
    public void setYwmc(String ywmc) {
        this.ywmc = ywmc == null ? null : ywmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jx_zy.xy
     *
     * @return the value of t_jx_zy.xy
     *
     * @mbg.generated
     */
    public String getXy() {
        return xy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jx_zy.xy
     *
     * @param xy the value for t_jx_zy.xy
     *
     * @mbg.generated
     */
    public void setXy(String xy) {
        this.xy = xy == null ? null : xy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jx_zy.xsh
     *
     * @return the value of t_jx_zy.xsh
     *
     * @mbg.generated
     */
    public String getXsh() {
        return xsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jx_zy.xsh
     *
     * @param xsh the value for t_jx_zy.xsh
     *
     * @mbg.generated
     */
    public void setXsh(String xsh) {
        this.xsh = xsh == null ? null : xsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jx_zy.lb
     *
     * @return the value of t_jx_zy.lb
     *
     * @mbg.generated
     */
    public String getLb() {
        return lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jx_zy.lb
     *
     * @param lb the value for t_jx_zy.lb
     *
     * @mbg.generated
     */
    public void setLb(String lb) {
        this.lb = lb == null ? null : lb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jx_zy.zygb
     *
     * @return the value of t_jx_zy.zygb
     *
     * @mbg.generated
     */
    public String getZygb() {
        return zygb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jx_zy.zygb
     *
     * @param zygb the value for t_jx_zy.zygb
     *
     * @mbg.generated
     */
    public void setZygb(String zygb) {
        this.zygb = zygb == null ? null : zygb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jx_zy.zt
     *
     * @return the value of t_jx_zy.zt
     *
     * @mbg.generated
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jx_zy.zt
     *
     * @param zt the value for t_jx_zy.zt
     *
     * @mbg.generated
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_zy
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", zy=").append(zy);
        sb.append(", mc=").append(mc);
        sb.append(", ywmc=").append(ywmc);
        sb.append(", xy=").append(xy);
        sb.append(", xsh=").append(xsh);
        sb.append(", lb=").append(lb);
        sb.append(", zygb=").append(zygb);
        sb.append(", zt=").append(zt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}