package com.web.testssm.dao;

import com.web.testssm.entity.KwKcap;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface KwKcapMapper {
    List<KwKcap> test();
    List<Map<String, Object>> test1(@Param("kcxh")String kcxh, @Param("zy") String zy);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kw_kcap
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kw_kcap
     *
     * @mbg.generated
     */
    int insert(KwKcap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kw_kcap
     *
     * @mbg.generated
     */
    int insertSelective(KwKcap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kw_kcap
     *
     * @mbg.generated
     */
    KwKcap selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kw_kcap
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KwKcap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kw_kcap
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KwKcap record);
}