package com.web.testssm.dao;

import com.web.testssm.entity.KwXkXx;

public interface KwXkXxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kw_xk_xx
     *
     * @mbg.generated
     */
    int insert(KwXkXx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kw_xk_xx
     *
     * @mbg.generated
     */
    int insertSelective(KwXkXx record);
}