package com.web.testssm.dao;

import com.web.testssm.entity.TJxZy;

public interface TJxZyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_zy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String zy);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_zy
     *
     * @mbg.generated
     */
    int insert(TJxZy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_zy
     *
     * @mbg.generated
     */
    int insertSelective(TJxZy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_zy
     *
     * @mbg.generated
     */
    TJxZy selectByPrimaryKey(String zy);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_zy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TJxZy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_zy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TJxZy record);
}